### ISSUE TITLE
Items browse inaccessible after bulk delete

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/NumericDataTypes#15]
I imported items using a CSV to test #14 (timestamp) and then created some items manually to test other conversions. I used "delete selected" to remove 25 of these items, which contain a mix of fields using timestamp, duration, and interval data. 

The items deleted, but now if NumericDataTypes is active, when I try to access `/admin/item`, I get the following messages:

```
Exception
Failed calling Omeka\Api\Representation\ValueRepresentation::jsonSerialize()

Details:

exception 'InvalidArgumentException' with message 'Invalid datetime string, must use ISO 8601' in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/src/DataType/AbstractDateTimeDataType.php:47
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/src/DataType/Timestamp.php(27): NumericDataTypes\DataType\AbstractDateTimeDataType::getDateTimeFromValue('1982-02-06T01:0...')
#1 /websites/omekadev/home/www/mebrett/testomekas/application/src/Api/Representation/ValueRepresentation.php(67): NumericDataTypes\DataType\Timestamp->getJsonLd(Object(Omeka\Api\Representation\ValueRepresentation))
#2 [internal function]: Omeka\Api\Representation\ValueRepresentation->jsonSerialize()
#3 /websites/omekadev/home/www/mebrett/testomekas/application/src/Api/Representation/AbstractResourceRepresentation.php(290): json_encode(Object(Omeka\Api\Representation\ItemRepresentation))
#4 /websites/omekadev/home/www/mebrett/testomekas/application/Module.php(134): Omeka\Api\Representation\AbstractResourceRepresentation->embeddedJsonLd()
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Module->Omeka\{closure}(Object(Zend\EventManager\Event))
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#7 /websites/omekadev/home/www/mebrett/testomekas/application/src/View/Helper/Trigger.php(61): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#8 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.browse.aft...')
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#10 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/admin/item/browse.phtml(136): Zend\View\Renderer\PhpRenderer->__call('trigger', Array)
#11 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/admin/item/browse.phtml(136): Zend\View\Renderer\PhpRenderer->trigger('view.browse.aft...')
#12 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/websites/omeka...')
#13 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#14 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#15 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#16 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#17 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#18 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#20 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#21 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#22 {main}

Next exception 'Exception' with message 'Failed calling Omeka\Api\Representation\ValueRepresentation::jsonSerialize()' in /websites/omekadev/home/www/mebrett/testomekas/application/src/Api/Representation/AbstractResourceRepresentation.php:290
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/application/src/Api/Representation/AbstractResourceRepresentation.php(0): json_encode()
#1 /websites/omekadev/home/www/mebrett/testomekas/application/Module.php(134): Omeka\Api\Representation\AbstractResourceRepresentation->embeddedJsonLd()
#2 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Module->Omeka\{closure}(Object(Zend\EventManager\Event))
#3 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#4 /websites/omekadev/home/www/mebrett/testomekas/application/src/View/Helper/Trigger.php(61): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#5 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.browse.aft...')
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#7 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/admin/item/browse.phtml(136): Zend\View\Renderer\PhpRenderer->__call('trigger', Array)
#8 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/admin/item/browse.phtml(136): Zend\View\Renderer\PhpRenderer->trigger('view.browse.aft...')
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/websites/omeka...')
#10 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#11 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#13 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#16 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#17 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#18 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#19 {main}
```

**Comment by mebrett** [comment]
After Jim asked, I determined that there were items with timestamp and interval values with offset from testing the Offset branch. Once I deleted those items (with the module deactivated) I was able to activate the module and access items normally.
